### ISSUE TITLE
Up to date version

### ISSUE THREAD

**Issue by psych0v0yager** [Qudix/template-commonlibsse-ng#1]
Hey I have made an up to date version of this template found here
https://github.com/psych0v0yager/CommonLibSSE-NG-xmake-template

This template currently points to my clone of the xmake-repo
https://github.com/psych0v0yager/xmake-repo/tree/dev

I needed to clone the repo because xmake-repo points to an old version of CommonLibSSE (v3.7.0) that doesnt work with Skyrim .1130 and up. I wasn't sure which fork is more stable so I also tried to point it to AlanTse's fork as well (https://github.com/alandtse/CommonLibVR/tree/ng) 

My xmake-repo works; however, it looks fairly janky as you have to pass in the hash rather than a version number. Also the option for AlanTse's fork isnt working. 

Did you write the commonlibsse entry inside xmake-repo? If so do you mind looking over my clone? I would like to make it a little easier to use before pushing to the xmake-repo devs. IMO xmake is the easiest way to work with C++ and will help a lot of new modders get into C++ modding.

Thanks

**Comment by qudix** [comment]
I had already added xmake support in commonlibsse (po3 and ng), I just forgot to update this template to reflect that before.

I also just remembered that it might not work on alandtse's version without some tweaks, and even then the OpenVR version that it requires is not really available.

**Comment by psych0v0yager** [comment]
Hell yeah, I’m still new to C++ and this template has already helped me a ton. I appreciate the quick response.

**Comment by psych0v0yager** [comment]
@qudix by any chance do you use vscode? How did you set up the intellisense autocomplete to work with this project?

**Comment by psych0v0yager** [comment]
@qudix are you using vscode by any chance? I cloned this template and ran xmake update intellisense, yet I am not getting autocomplete options for RE:: and SKSE::
